#!/bin/bash
# Simple test to verify XML structure

cat > /tmp/expected_xml.xml << 'EOF'
<?xml version="1.0"?>
<!--Generated by BranchForge - Behavior Tree XML-->
<BehaviorTree name="SampleBehaviorTree" description="Sample navigation behavior tree generated by BranchForge" version="1.0" root_node_id="root" generator="BranchForge">
  <Node id="root" type="Sequence" name="MainSequence" x="400" y="200"/>
  <Node id="action1" type="Action" name="NavigateToGoal" x="300" y="300" parent_id="root">
    <Parameter name="goal" value="${navigation_goal}"/>
  </Node>
  <Node id="action2" type="Action" name="SendStatus" x="500" y="300" parent_id="root">
    <Parameter name="message" value="Goal reached"/>
  </Node>
</BehaviorTree>
EOF

echo "Expected XML structure created at /tmp/expected_xml.xml"
cat /tmp/expected_xml.xml