#include "ui/MainWindow.h"
#include "project/BehaviorTreeXML.h"
#include <QFileDialog>
#include <QStandardPaths>
#include <QLoggingCategory>

Q_LOGGING_CATEGORY(uiMain, "branchforge.ui.mainwindow")

namespace BranchForge::UI {

MainWindow::MainWindow(QObject* parent)
    : QObject(parent)
{
    qCInfo(uiMain) << "MainWindow created";
    updateTitle();
}

MainWindow::~MainWindow() = default;

void MainWindow::setIsDarkMode(bool darkMode) {
    if (m_isDarkMode != darkMode) {
        m_isDarkMode = darkMode;
        qCInfo(uiMain) << "Dark mode changed to:" << darkMode;
        emit isDarkModeChanged();
    }
}

void MainWindow::newProject() {
    qCInfo(uiMain) << "Creating new project";
    
    QString projectPath = QFileDialog::getSaveFileName(
        nullptr,
        "Create New BranchForge Project",
        QStandardPaths::writableLocation(QStandardPaths::DocumentsLocation) + "/Untitled.bfproj",
        "BranchForge Projects (*.bfproj)"
    );
    
    if (!projectPath.isEmpty()) {
        m_currentProjectPath = projectPath;
        updateTitle();
        emit projectChanged();
        qCInfo(uiMain) << "New project created at:" << projectPath;
    }
}

void MainWindow::openProject() {
    qCInfo(uiMain) << "Opening project";
    
    QString projectPath = QFileDialog::getOpenFileName(
        nullptr,
        "Open BranchForge Project",
        QStandardPaths::writableLocation(QStandardPaths::DocumentsLocation),
        "BranchForge Projects (*.bfproj)"
    );
    
    if (!projectPath.isEmpty()) {
        m_currentProjectPath = projectPath;
        updateTitle();
        emit projectChanged();
        qCInfo(uiMain) << "Project opened:" << projectPath;
    }
}

void MainWindow::saveProject() {
    if (m_currentProjectPath.isEmpty()) {
        newProject();
        return;
    }
    
    qCInfo(uiMain) << "Saving project:" << m_currentProjectPath;
    // TODO: Implement actual saving logic
}

void MainWindow::exportXML() {
    qCInfo(uiMain) << "Exporting behavior tree to XML";
    
    QString exportPath = QFileDialog::getSaveFileName(
        nullptr,
        "Export Behavior Tree XML",
        QStandardPaths::writableLocation(QStandardPaths::DocumentsLocation) + "/behavior_tree.xml",
        "XML Files (*.xml)"
    );
    
    if (!exportPath.isEmpty()) {
        qCInfo(uiMain) << "Exporting behavior tree to:" << exportPath;
        
        // Create a sample behavior tree for demonstration
        using namespace BranchForge::Project;
        BehaviorTreeXML btXML;
        btXML.setTreeName("SampleBehaviorTree");
        btXML.setTreeDescription("Sample navigation behavior tree generated by BranchForge");
        btXML.setRootNodeId("root");
        
        // Create a simple sequence with action nodes
        BTXMLNode rootNode;
        rootNode.id = "root";
        rootNode.type = "Sequence";
        rootNode.name = "MainSequence";
        rootNode.position = QPointF(400, 200);
        
        BTXMLNode actionNode1;
        actionNode1.id = "action1";
        actionNode1.type = "Action";
        actionNode1.name = "NavigateToGoal";
        actionNode1.position = QPointF(300, 300);
        actionNode1.parameters["goal"] = "${navigation_goal}";
        actionNode1.parentId = "root";
        
        BTXMLNode actionNode2;
        actionNode2.id = "action2";
        actionNode2.type = "Action";
        actionNode2.name = "SendStatus";
        actionNode2.position = QPointF(500, 300);
        actionNode2.parameters["message"] = "Goal reached";
        actionNode2.parentId = "root";
        
        // Add nodes to the tree
        btXML.addNode(rootNode);
        btXML.addNode(actionNode1);
        btXML.addNode(actionNode2);
        
        // Export to XML file
        if (btXML.exportToFile(exportPath)) {
            qCInfo(uiMain) << "Successfully exported behavior tree XML to:" << exportPath;
        } else {
            qCWarning(uiMain) << "Failed to export behavior tree XML";
        }
    }
}

void MainWindow::updateTitle() {
    QString newTitle = "BranchForge";
    if (!m_currentProjectPath.isEmpty()) {
        QFileInfo fileInfo(m_currentProjectPath);
        newTitle += " - " + fileInfo.baseName();
    }
    
    if (m_title != newTitle) {
        m_title = newTitle;
        emit titleChanged();
    }
}

} // namespace BranchForge::UI