name: Core Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  core-tests:
    name: Core Unit Tests
    runs-on: ubuntu-22.04  # Use 22.04 for better ROS2 support
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install basic dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          pkg-config \
          libgtest-dev \
          qt6-base-dev \
          qt6-declarative-dev \
          libqt6xml6-dev

    - name: Setup minimal ROS2 (Humble - Ubuntu 22.04)
      run: |
        # Add ROS 2 apt repository
        sudo apt-get install -y software-properties-common curl
        curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu jammy main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
        
        sudo apt-get update
        sudo apt-get install -y \
          ros-humble-ros-core \
          ros-humble-rclcpp \
          ros-humble-ament-cmake \
          python3-colcon-common-extensions

    - name: Install BehaviorTree.CPP
      run: |
        cd /tmp
        git clone https://github.com/BehaviorTree/BehaviorTree.CPP.git --depth 1 --branch v4.6
        cd BehaviorTree.CPP
        mkdir build && cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF -DBUILD_EXAMPLES=OFF
        make -j$(nproc)
        sudo make install
        sudo ldconfig

    - name: Build BranchForge
      run: |
        source /opt/ros/humble/setup.bash
        colcon build --packages-select branchforge \
          --cmake-args -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=ON

    - name: Run Core Tests
      run: |
        source /opt/ros/humble/setup.bash
        source install/setup.bash
        
        echo "=== Running BranchForge Core Tests ==="
        
        # Run the working BehaviorTreeXML test
        if [ -f "build/branchforge/tests/unit/test_behavior_tree_xml" ]; then
          echo "Running BehaviorTreeXML tests..."
          ./build/branchforge/tests/unit/test_behavior_tree_xml --gtest_output=xml:behaviortree_xml_results.xml
          echo "✅ BehaviorTreeXML tests completed"
        else
          echo "❌ BehaviorTreeXML test not found"
          ls -la build/branchforge/tests/unit/ || echo "Tests directory not found"
          exit 1
        fi

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: core-test-results
        path: "*.xml"